// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbwcOJtmMPSojdzVKCh0gX9CUjUBZUOyA',
    appId: '1:357203092219:web:12b427180b8bd821ac465e',
    messagingSenderId: '357203092219',
    projectId: 'movie-5a2ae',
    authDomain: 'movie-5a2ae.firebaseapp.com',
    storageBucket: 'movie-5a2ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXsrhzAk7hbk1xqAKB67r7O80JarTeMGc',
    appId: '1:357203092219:android:26e9affb24714946ac465e',
    messagingSenderId: '357203092219',
    projectId: 'movie-5a2ae',
    storageBucket: 'movie-5a2ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpP1WtHVhR1h9qY6F1jpPU2G-Obq1V14',
    appId: '1:357203092219:ios:1c77fd9991b780a1ac465e',
    messagingSenderId: '357203092219',
    projectId: 'movie-5a2ae',
    storageBucket: 'movie-5a2ae.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpP1WtHVhR1h9qY6F1jpPU2G-Obq1V14',
    appId: '1:357203092219:ios:da26b00e0896cdefac465e',
    messagingSenderId: '357203092219',
    projectId: 'movie-5a2ae',
    storageBucket: 'movie-5a2ae.appspot.com',
    iosBundleId: 'com.example.moviesapp.RunnerTests',
  );
}
